"""document generator

Revision ID: 2590cbec7427
Revises: 8710efa5c0ea
Create Date: 2026-07-25 09:34:05.740208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2590cbec7427'
down_revision: Union[str, None] = '8710efa5c0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_documents',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_documents')
    # ### end Alembic commands ###
