"""knowledge graph

Revision ID: 3af6d68f7b2b
Revises: 9af6735bf61a
Create Date: 2026-07-23 20:08:19.864570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3af6d68f7b2b'
down_revision: Union[str, None] = '9af6735bf61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_graph_nodes',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('concept_key', sa.String(length=150), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('completion', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('business_value', sa.Integer(), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('validation_rules', sa.JSON(), nullable=False),
    sa.Column('missing_information', sa.JSON(), nullable=False),
    sa.Column('captured_data', sa.JSON(), nullable=False),
    sa.Column('generated_questions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'concept_key', name='uq_kg_node_project_concept')
    )
    op.create_index(op.f('ix_knowledge_graph_nodes_concept_key'), 'knowledge_graph_nodes', ['concept_key'], unique=False)
    op.create_table('knowledge_graph_edges',
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_node_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dependency_node_id'], ['knowledge_graph_nodes.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_graph_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'dependency_node_id', name='uq_kg_edge_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_graph_nodes_concept_key'), table_name='knowledge_graph_nodes')
    op.drop_table('knowledge_graph_nodes')
    # ### end Alembic commands ###
