"""security engine

Revision ID: 8710efa5c0ea
Revises: c51aed696fe7
Create Date: 2026-07-25 09:23:18.874213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8710efa5c0ea'
down_revision: Union[str, None] = 'c51aed696fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_analyses',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('threat_model', sa.JSON(), nullable=False),
    sa.Column('rbac_matrix', sa.JSON(), nullable=False),
    sa.Column('risk_register', sa.JSON(), nullable=False),
    sa.Column('security_checklist', sa.JSON(), nullable=False),
    sa.Column('privacy_impact_assessment', sa.JSON(), nullable=False),
    sa.Column('data_classification', sa.JSON(), nullable=False),
    sa.Column('security_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_analyses')
    # ### end Alembic commands ###
