"""interview engine

Revision ID: a36a66b52b23
Revises: 3af6d68f7b2b
Create Date: 2026-07-23 22:45:12.037940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a36a66b52b23'
down_revision: Union[str, None] = '3af6d68f7b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_sessions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pending_concept_key', sa.String(length=150), nullable=True),
    sa.Column('pending_question', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_turns',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('concept_key', sa.String(length=150), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('completion_delta', sa.Integer(), nullable=False),
    sa.Column('confidence_delta', sa.Integer(), nullable=False),
    sa.Column('consultant_note', sa.Text(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_turns')
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
