"""requirement engine

Revision ID: c51aed696fe7
Revises: a36a66b52b23
Create Date: 2026-07-24 20:33:25.938810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c51aed696fe7'
down_revision: Union[str, None] = 'a36a66b52b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_key', sa.String(length=20), nullable=False),
    sa.Column('requirement_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('business_goal', sa.Text(), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('actors', sa.JSON(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('security_controls', sa.JSON(), nullable=False),
    sa.Column('database_tables', sa.JSON(), nullable=False),
    sa.Column('api_endpoints', sa.JSON(), nullable=False),
    sa.Column('ui_screens', sa.JSON(), nullable=False),
    sa.Column('test_cases', sa.JSON(), nullable=False),
    sa.Column('source_concept_key', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'requirement_key', name='uq_requirement_project_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirements')
    # ### end Alembic commands ###
