"""review engine

Revision ID: dba5a668f1a2
Revises: 2590cbec7427
Create Date: 2026-07-25 15:12:34.338520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dba5a668f1a2'
down_revision: Union[str, None] = '2590cbec7427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('rule_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('completeness_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('security_score', sa.Integer(), nullable=False),
    sa.Column('architecture_score', sa.Integer(), nullable=False),
    sa.Column('business_score', sa.Integer(), nullable=False),
    sa.Column('testing_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('approved_for_export', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_runs')
    # ### end Alembic commands ###
