"""cascade deletes for project-owned tables

Revision ID: df4132b0bde7
Revises: dba5a668f1a2
Create Date: 2026-07-26 01:12:36.282081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df4132b0bde7'
down_revision: Union[str, None] = 'dba5a668f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('generated_documents_project_id_fkey'), 'generated_documents', type_='foreignkey')
    op.create_foreign_key('generated_documents_project_id_fkey', 'generated_documents', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('interview_sessions_project_id_fkey'), 'interview_sessions', type_='foreignkey')
    op.create_foreign_key('interview_sessions_project_id_fkey', 'interview_sessions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('interview_turns_session_id_fkey'), 'interview_turns', type_='foreignkey')
    op.create_foreign_key('interview_turns_session_id_fkey', 'interview_turns', 'interview_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('knowledge_graph_edges_node_id_fkey'), 'knowledge_graph_edges', type_='foreignkey')
    op.drop_constraint(op.f('knowledge_graph_edges_dependency_node_id_fkey'), 'knowledge_graph_edges', type_='foreignkey')
    op.create_foreign_key('knowledge_graph_edges_dependency_node_id_fkey', 'knowledge_graph_edges', 'knowledge_graph_nodes', ['dependency_node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('knowledge_graph_edges_node_id_fkey', 'knowledge_graph_edges', 'knowledge_graph_nodes', ['node_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('knowledge_graph_nodes_project_id_fkey'), 'knowledge_graph_nodes', type_='foreignkey')
    op.create_foreign_key('knowledge_graph_nodes_project_id_fkey', 'knowledge_graph_nodes', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('memberships_organization_id_fkey'), 'memberships', type_='foreignkey')
    op.drop_constraint(op.f('memberships_user_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key('memberships_organization_id_fkey', 'memberships', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('memberships_user_id_fkey', 'memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('projects_organization_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key('projects_organization_id_fkey', 'projects', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('requirements_project_id_fkey'), 'requirements', type_='foreignkey')
    op.create_foreign_key('requirements_project_id_fkey', 'requirements', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('review_runs_project_id_fkey'), 'review_runs', type_='foreignkey')
    op.create_foreign_key('review_runs_project_id_fkey', 'review_runs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('security_analyses_project_id_fkey'), 'security_analyses', type_='foreignkey')
    op.create_foreign_key('security_analyses_project_id_fkey', 'security_analyses', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('security_analyses_project_id_fkey', 'security_analyses', type_='foreignkey')
    op.create_foreign_key(op.f('security_analyses_project_id_fkey'), 'security_analyses', 'projects', ['project_id'], ['id'])
    op.drop_constraint('review_runs_project_id_fkey', 'review_runs', type_='foreignkey')
    op.create_foreign_key(op.f('review_runs_project_id_fkey'), 'review_runs', 'projects', ['project_id'], ['id'])
    op.drop_constraint('requirements_project_id_fkey', 'requirements', type_='foreignkey')
    op.create_foreign_key(op.f('requirements_project_id_fkey'), 'requirements', 'projects', ['project_id'], ['id'])
    op.drop_constraint('projects_organization_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_organization_id_fkey'), 'projects', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint('memberships_user_id_fkey', 'memberships', type_='foreignkey')
    op.drop_constraint('memberships_organization_id_fkey', 'memberships', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_user_id_fkey'), 'memberships', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('memberships_organization_id_fkey'), 'memberships', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint('knowledge_graph_nodes_project_id_fkey', 'knowledge_graph_nodes', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_graph_nodes_project_id_fkey'), 'knowledge_graph_nodes', 'projects', ['project_id'], ['id'])
    op.drop_constraint('knowledge_graph_edges_node_id_fkey', 'knowledge_graph_edges', type_='foreignkey')
    op.drop_constraint('knowledge_graph_edges_dependency_node_id_fkey', 'knowledge_graph_edges', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_graph_edges_dependency_node_id_fkey'), 'knowledge_graph_edges', 'knowledge_graph_nodes', ['dependency_node_id'], ['id'])
    op.create_foreign_key(op.f('knowledge_graph_edges_node_id_fkey'), 'knowledge_graph_edges', 'knowledge_graph_nodes', ['node_id'], ['id'])
    op.drop_constraint('interview_turns_session_id_fkey', 'interview_turns', type_='foreignkey')
    op.create_foreign_key(op.f('interview_turns_session_id_fkey'), 'interview_turns', 'interview_sessions', ['session_id'], ['id'])
    op.drop_constraint('interview_sessions_project_id_fkey', 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('interview_sessions_project_id_fkey'), 'interview_sessions', 'projects', ['project_id'], ['id'])
    op.drop_constraint('generated_documents_project_id_fkey', 'generated_documents', type_='foreignkey')
    op.create_foreign_key(op.f('generated_documents_project_id_fkey'), 'generated_documents', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
